Add support for OverExtended (Ox)
xFutte/qb-newspaper pull request #33
Opened 2024-01-16 18:37 UTC by Amrizamaa

Hello, 

Find here the modification to add support for Ox Inventory and Ox Target

I edited the config.lua to add the variables
I edited Client Side to add the Ox Target support 
I edited Server Side to add the Ox Inventory support

Have a good day

2024-01-16 19:12 UTC, xFutte requested changes

2024-01-16 19:12 UTC, xFutte commented on server/server.lua
> +            TriggerClientEvent('QBCore:Notify', source, '$' .. Config.Price .. ' requis pour acheter un journal',
Messages should be in english.

2024-01-16 19:12 UTC, xFutte commented on config.lua
> +Config.Target = "ox" -- ox or qb-target
Default to qb instead

2024-01-16 22:59 UTC, Amrizamaa commented
Change done

2024-03-08 01:19 UTC, xFutte commented on server/server.lua
> +    local cash = Player.PlayerData.money['bank']
It should not be from the bank but from cash.

2024-03-08 01:21 UTC, xFutte commented on locales/en.lua
Please use camel case for the table keys.

2024-03-08 01:22 UTC, xFutte requested changes
See review changes.

2025-07-17 21:50 UTC, closed without merging